### PR TITLE
Fix filename sanitization (for e.g. Twitter)

### PR DESCRIPTION
**Pull request by 54ac**
Hi, this is a quick fix for the sanitization of newer Twitter filenames (`filename?format=jpg`) and for properly recognizing their filenames (previous regex removed the entire string if no `.` was found).

### CODE REVIEW

**Comment by mcdamo** [comment]
Thankyou, this is a nice simple fix.

Resolve the review and I can merge, otherwise close I can make the change in master.

**Comment by 54ac** [comment]
Should be fine now.

**Comment by mcdamo** [comment]
> Should be fine now, you can merge.

Wrong changes merged? `getFilename` still showing unwanted changes, while your fix to `getPathPart` has disappeared.

**Comment by 54ac** [comment]
getFilePart is already fine in 4.3.0, only getFilename remains, but I'm not sure if it's necessary now.

**Pull request closed without merging**
